version: '3.7'

services:
  pathway:
    build:
#     args:
#       - without_biocyc=0
      context: .
#   command: ["-www-publish", "ORGANISM_ID"]
    # xvfb-run requires init in the container
    init: true
    ports:
    - "1555:1555"
#   volumes:
#     - "./ptools-local:/opt/ptools-local"
